#78 remove notebooks code reliant valkyrie
nsidc/NSIDC-Data-Tutorials pull request #80
Opened 2024-08-05 16:45 UTC by trey-stafford

Resolves #78 

This removes all of the notebooks and code, except for:

* The `01_introduction` notebook, which now only contains overview information about (pre)icebridge/icesat/icesat2 altimetry data. It does not provide any code for searching/accessing/harmonizing data.
* The `corrections` notebook. This remains unchanged, describing to users the importance of harmonizing the CRS of data across missions, and using a synthesized dataset as an example
    * We will address adding a real-world example to the `corrections` notebook in #76

2024-08-05 18:28 UTC, trey-stafford commented
PR to resolve failing tests: https://github.com/nsidc/NSIDC-Data-Tutorials/pull/81

2025-05-20 15:53 UTC, asteiker requested changes

2025-05-20 15:53 UTC, asteiker commented on README.md
@trey-stafford Thoughts on updating the name of this section? I'd rather it not say "IceFlow" since that's the name of the new library, and we want to remove all references to the original IceFlow here. Maybe something like "Altimetry_Harmonization"?

2025-05-20 15:53 UTC, asteiker commented on notebooks/iceflow/0_introduction.ipynb
Same comment as above on "IceFlow" - perhaps we remove references to that name in this notebook.

2025-05-20 15:53 UTC, asteiker commented on notebooks/iceflow/README.md
I  think we'll want to have a pointer to the new iceflow library here. I can make some suggested changes directly - just wanted to add my comment in the meantime!

2025-05-20 16:21 UTC, trey-stafford commented on README.md
Yes, good idea! 4f3753e

2025-05-20 16:21 UTC, trey-stafford commented on notebooks/iceflow/0_introduction.ipynb
4f3753e

2025-05-21 15:27 UTC, betolink commented
The changes look good to me!

2025-05-21 16:22 UTC, mikala-nsidc commented
In the 01-introduction notebook the link to OpenAltimetry should be updated to:

https://openaltimetry.earthdatacloud.nasa.gov/data/

Otherwise that notebook looks good to me!  Still need to read through corrections.

2025-05-21 16:29 UTC, mikala-nsidc commented
Nevermind about corrections notebook!  I needed to read the description of the PR more carefully above.

2025-05-21 17:17 UTC, trey-stafford commented
> In the 01-introduction notebook the link to OpenAltimetry should be updated to:
> 
> https://openaltimetry.earthdatacloud.nasa.gov/data/
> 
> Otherwise that notebook looks good to me! Still need to read through corrections.

Good catch! There were some other outdated references as well, so I fixed those too. e0b0db5

2025-05-21 17:37 UTC, andypbarrett commented on notebooks/altimetry_harmonization/0_introduction.ipynb
> +{
<p>Is "Altimetry Harmonization" the best title? I think it is misleading, the page does not give any information about harmonization, just background to the missions.</p><p> </p><p>Introduce both this notebook and "corrections" notebook.</p><p> </p><p>In section 1. we say the notebook is interactive but there is no code to interact with, it is just a text document.  Suggest combing the two notebooks.</p><p> </p><p>The "pre-IceBridge" flights seem like an add-on.  If we are providing a chronological introduction to NASA Cryosphere Altimetry missions, then we should start with ATM.</p><p> </p><p>None of these missions measure ice thickness directly, they measure land, vegetation, ice, sea ice and ocean surface heights.  Thickness and change in thickness are derived products.</p><p> </p><p>Suggest introducing the missions (sections 2.1 - 2.4) before discussing the differences in file formats and reference frames.</p><p> </p><p>Need information on what the file formats are and how to read them.</p><p> </p><p>I would also add a table of the ITRF that correspond to the four products, and any changes that have occurred.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/nsidc/NSIDC-Data-Tutorials/pull/80/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='0'/>

2025-05-21 22:49 UTC, andypbarrett commented
@asteiker and @trey-stafford , I wonder if the materials here could be incorporated into the iceflow notebooks.  They seem to be isolated here.  Alternatively, we could incorporate them into the NSIDC Data Cookbook.

A path forward might be to merge this PR, assuming we are not losing any useful information, and then open an issue in the Cookbook to incorporate the material there.

An alternative would be to incorporate the information into the UW E-Science ICESat-2 Cookbook.

That said, we could do both.  There is no harm in repetition or duplication

2025-06-04 20:40 UTC, trey-stafford commented
Following discussions between myself and @asteiker, we decided to migrate the `0_introduction.ipynb` and `corrections.ipynb` to the [iceflow](https://github.com/nsidc/iceflow) repository (see https://github.com/nsidc/iceflow/pull/70).

The top-level README for this repository has been updated to point users to the `iceflow` repository and documentation. All other iceflow-related content has been removed.

2025-06-12 14:41 UTC, merged